-- =====================================================
-- NEUTRALIZED 2026-07-25 — this migration never applied and must not start applying now.
-- Original intent: SECURITY HARDENING: CVE-2025-48757 COMPLIANCE (dated 2026-01-04)
--   "Address remaining SECURITY DEFINER functions missing search_path and add RLS audit checks"
--   Reference: https://www.superblocks.com/blog/lovable-vulnerabilities
-- =====================================================
--
-- WHY THIS FILE IS EMPTY
--
-- It was never applied. Verified against the live project (jmjiyekmxwsxkfnqwyaa):
--   SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version='20260104100000' -> 0
-- while migrations through 20260724112042 are recorded. It is skipped permanently because the
-- deploy applies versions newer than the last-applied one, and this timestamp is ~7 months behind.
--
-- It also could not have applied, twice over:
--   1. It used `CREATE POLICY IF NOT EXISTS`, which PostgreSQL does not support (syntax error).
--   2. It used `CREATE OR REPLACE FUNCTION public.increment_rate_limit(...)` to change the return
--      type from TABLE(count, remaining, allowed) to TABLE(allowed, remaining). CREATE OR REPLACE
--      cannot change a function's return type; that requires DROP + CREATE.
--   Its rate_limits table definition (rate_key/request_count/window_start) also disagrees with the
--   live table created by 20251119052746 (key/count/expires_at).
--
-- WHY IT WAS NOT REPAIRED INSTEAD
--
-- Making it applicable would be a regression, not a fix. It carries CREATE OR REPLACE bodies for
-- ~12 functions as they stood in January. At least one — public.get_channel_permissions — was
-- deliberately redefined later by 20260414000000_consolidate_channel_members.sql. Replaying this
-- file on the next deploy would silently revert that function to its superseded definition.
--
-- WHAT WAS ACTUALLY LOST, AND WHY IT IS NOT A GAP
--
-- * search_path hardening on the listed SECURITY DEFINER functions: not needed. Supabase's
--   security advisors report zero function_search_path_mutable findings for this project, so the
--   live definitions already set search_path.
-- * The live increment_rate_limit is the ORIGINAL, working definition matching the live
--   rate_limits table. Rate limiting is functional; nothing here needs to land.
-- * public.audit_rls_status() was never created. It is not referenced by any application code.
--   Its purpose — asserting RLS coverage — is better served by a CI check over the migration
--   tree than by a database function nothing calls. All 116 live public tables currently report
--   rowsecurity = true.
--
-- The file is kept (rather than deleted) so the version stays present in the migration tree and
-- ordering is unchanged. Do not add statements here — write a new timestamped migration instead.
